config/routes.rb
Brainbox::Application.routes.draw do
  get "preferences/index"

  get "preferences/edit", :as => :preferences

  resources :comments
  resources :calendar_events
  resources :super_files do
    collection do
      post 'create_many', :action => 'create_many'
    end
  end
  resources :sections do
    resources :assignments do
      resources :submissions
    end
  end
  resources :courses
  resources :schools

  get "help" => "help#index"
  get '/' => "home#index", :as => :home

  devise_for :users, :controllers => { 
    :confirmations => "confirmations",
    :passwords => "passwords",
    :registrations => "registrations",
    :sessions => "sessions",
  }

  # user entry points
  get '/admin/users' => "users#index", :as => :users
  get '/admin/users/new' => "users#new", :as => :new_user
  post '/admin/users/create' => "users#create", :as => :create_user
  get '/admin/users/edit' => "users#edit", :as => :edit_user
  patch '/admin/users/update' => "users#update", :as => :update_user
  get '/admin/users/:id' => "users#show", :as => :show_user

  get "home/index"

  root :to => "home#index"

  post 'feedback/create' => 'feedback#create', :as => 'feedback'
  get 'manage_courses' => 'sections#index', :as => 'manage_courses'
end

app/models/section.rb
class Section < ActiveRecord::Base
	attr_accessible :name, :start, :finish, :description, :location, :capacity, :announcements

  has_and_belongs_to_many :teachers, :class_name => :User, :join_table => :teachers_sections
  has_and_belongs_to_many :students, :class_name => :User, :join_table => :students_sections
  belongs_to :course
  has_many :assignments

  validates :name, :presence => true
  validates :start, :presence => true
  validates :finish, :presence => true

  def can_update attribute
    self.teachers.include? @current_user
  end

  def can_delete
    self.teachers.include? @current_user
  end

  # teachers
  def add_teacher user
    if not self.teachers.include? user
      self.teachers << user
    end
  end

  def remove_teacher user
    self.teachers.delete user
  end

  # students
  def add_student user
    if not self.students.include? user
      self.students << user
    end
  end

  def remove_student user
    self.students.delete user
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  # GET /sections
  # GET /sections.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])
    @assignments = @section.assignments
    @tab = 'Overview'
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @section = Section.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
  end

  # POST /sections
  # POST /sections.json
  def create
    # transform dates from string to DateTime
    params[:section].strptime_params! ['start', 'finish']

    @section = Section.new(params[:section])

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render json: @section, status: :created, location: @section }
      else
        format.html { render action: "new" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    # transform dates from string to DateTime
    params[:section].strptime_params! ['start', 'finish']

    @section = Section.find(params[:id])

    respond_to do |format|
      if @section.update_attributes(params[:section])
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    @section.destroy

    respond_to do |format|
      format.html { redirect_to sections_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_admin_section_table.html.erb
<h2><%= title %></h2>

<table class="section-table table">
  <thead>
    <tr> 
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Location</th>
      <th>Capacity</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% sections.each do |section| %>
  <tr>
    <td><%= link_to section.name, section %></td>
    <td><%= section.start %></td>
    <td><%= section.finish %></td>
    <td><%= section.location %></td>
    <td><%= section.capacity %></td>
    <td><%= section.description[0..63] + (section.description.length > 64 ? '...' : '' )%></td>
    <td><%= link_to 'Edit', edit_section_path(section), :class => 'btn btn-warning btn-small' %></td>
    <td><%= link_to 'Delete', section, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
  </tr>
<% end %>
</table>

app/views/sections/_assignments.html.erb
<h2 class='header'>Assignments</h2>
<%= link_to '<i class="icon-plus icon-white"></i> New'.html_safe, new_section_assignment_path(@section), :class => 'btn btn-success', :style =>'margin-left: 20px; margin-top: -14px;' %>
<table class='table table-striped' style="margin-top:20px;">
  <tr>
    <th align='left' width='200'>Name</th>
    <th align='left' width='100'>Due</th>
    <th align='left' width='100'>Category</th>
    <th align='left' width='300'>Description</th>
    <th width='40'></th>
    <th width='37'></th>
    <th width='21'></th>
    <th width='34'></th>
  </tr>

<% @assignments.each do |assignment| %>
  <tr>
    <td><%= assignment.name %></td>
    <td><%= assignment.due %></td>
    <td><%= assignment.category %></td>
    <td><%= assignment.description %></td>
    <td></td>
    <td><%= link_to 'Details', section_assignment_path(@section, assignment), :class => 'btn btn-small' %></td>
    <td><%= link_to 'Edit', edit_section_assignment_path(@section, assignment), :class => 'btn btn-warning btn-small' %></td>
    <td><%= link_to 'Delete', section_assignment_path(@section, assignment), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-small' %></td>
  </tr>
<% end %>
</table>

<br />

app/views/sections/_calendar.html.erb
<div id='fullcalendar-container'></div>

app/views/sections/_files.html.erb
Files

app/views/sections/_form.html.erb
<%= form_for(@section, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field control-group">
    <%= f.label :name, :class => 'control-label', :for => 'section_name' %>
    <div class="controls"><%= f.text_field :name, :class => 'input-xxlarge' %></div>
  </div>
  <div class="field control-group">
    <%= f.label :start, :class => 'control-label', :for => 'section_start' %>
    <div class="controls"><%= render_datetime_picker @section, :start %></div>
  </div>
  <div class="field control-group">
    <%= f.label :finish, :class => 'control-label', :for => 'section_finish' %>
    <div class="controls"><%= render_datetime_picker @section, :finish %></div>
  </div>
  <div class="field control-group">
    <%= f.label :location, :class => 'control-label', :for => 'section_location' %>
    <div class="controls"><%= f.text_field :location %></div>
  </div>
  <div class="field control-group">
    <%= f.label :capacity, :class => 'control-label', :for => 'section_capacity' %>
    <div class="controls"><%= f.number_field :capacity, :class => 'input-small'%></div>
  </div>
  <div class="field control-group">
    <%= f.label :description, :class => 'control-label', :for => 'section_description' %>
    <div class="controls"><%= f.text_area :description, :class => 'input-xxlarge', :style => 'height: 80px;' %></div>
  </div>
  <div class="field control-group">
    <%= f.label :announcements, :class => 'control-label', :for => 'section_announcements' %>
    <div class="controls"><%= f.text_area :announcements, :class => 'input-xxlarge', :style => 'height: 120px;'%></div>
  </div>
  <div class="actions" style="margin-top:20px; margin-left: 180px;">
    <%= f.submit "Save", :class => 'btn btn-success' %> <%= link_to 'Cancel', @section, :class => 'btn' %>
  </div>
<% end %>

app/views/sections/_overview.html.erb
<h2 class='header'><%= @section.name %></h2>
<%= link_to 'Edit', edit_section_path(@section), :class => 'btn btn-warning flat', :style =>'margin-left: 20px; margin-top: -14px;' %>
<div class='class-details'>
<p><b>Taught by:</b> <%= @section.teachers.map{ |t| "#{t.first} #{t.last}" }.join(", ") %></p>
<p>
  <b>Starts at:</b>
  <%= @section.start %>
</p>

<p>
  <b>Finishes at:</b>
  <%= @section.finish %>
</p>

<p>
  <b>Location:</b>
  <%= @section.location %>
</p>

<p>
  <b>Class size:</b>
  <%= @section.capacity %>
</p>

<p class='class description'>
  <b>Description:</b>
  <%= @section.description %>
</p>

<p>
  <b>Announcements:</b>
  <%= @section.announcements %>
</p>
</div>
<!--<%= link_to 'Show All', section_assignments_path(@section), :class => 'btn' %>-->

<!--<%= "#{@section.teachers.count == 1 ? '' : 's'}" %>-->

app/views/sections/_section_table.html.erb
<h2><%= title %></h2>

<table class="section-table table">
  <thead>
    <tr> 
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Location</th>
      <th>Description</th>
    </tr>
  </thead>

<% sections.each do |section| %>
  <tr>
    <td><%= link_to section.name, section %></td>
    <td><%= format_date_for_form section.start %></td>
    <td><%= format_date_for_form section.finish %></td>
    <td><%= section.location %></td>
    <td><%= section.description[0..63] + (section.description.length > 63 ? '...' : '' )%></td>
  </tr>
<% end %>
</table>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

app/views/sections/index.html.erb
<% title "Manage Courses" %>

<% if not @sections_teaching.blank? %>
  <%= render :partial => 'admin_section_table', :locals => {:sections => @sections_teaching, :title => 'Courses I teach'} %>
<% end %>

<% if not @sections_taking.blank? %>
  <%= render :partial => 'section_table', :locals => {:sections => @sections_taking, :title => 'Courses I take'} %>
<% end %>

<% if @sections_teaching.blank? and @sections_taking.blank? %>
  <h3>You are not currently enrolled in, nor teaching, any classes.</h3>
<% end %>
<br/>

<%= link_to '<i class="icon-plus icon-white"></i> Add a course'.html_safe, new_section_path, :class => 'btn btn-primary pull-right' %>

app/views/sections/new.html.erb
<h1>Create a section</h1>

<%= render 'form' %>

app/views/sections/show.html.erb
<% title @section.name %>

<%= render_tabs @tab, {
    'Assignments' => render(:partial => 'assignments'),
    'Calendar' => render(:partial => 'calendar'),
    'Files' => render(:partial => 'files'),
    'Overview' => render(:partial => 'overview')
  }
%>