config/routes.rb
Brainbox::Application.routes.draw do
  get "preferences/index"

  get "preferences/edit", :as => :preferences

  resources :comments
  resources :calendar_events
  resources :super_files do
    collection do
      post 'create_many', :action => 'create_many'
    end
  end
  resources :sections do
    resources :assignments do
      resources :submissions
    end
  end
  resources :courses
  resources :schools

  get "help" => "help#index"
  get '/' => "home#index", :as => :home

  devise_for :users, :controllers => { 
    :confirmations => "confirmations",
    :passwords => "passwords",
    :registrations => "registrations",
    :sessions => "sessions",
  }

  # user entry points
  get '/admin/users' => "users#index", :as => :users
  get '/admin/users/new' => "users#new", :as => :new_user
  post '/admin/users/create' => "users#create", :as => :create_user
  get '/admin/users/edit' => "users#edit", :as => :edit_user
  patch '/admin/users/update' => "users#update", :as => :update_user
  get '/admin/users/:id' => "users#show", :as => :show_user

  get "home/index"

  root :to => "home#index"

  post 'feedback/create' => 'feedback#create', :as => 'feedback'
  get 'manage_courses' => 'sections#index', :as => 'manage_courses'
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  attr_accessible :note, :submitted, :super_files

  belongs_to :user
  belongs_to :assignment
  has_many :comments, :as => :commentable
  has_many :super_files, :as => :fileable

  before_create :add_submission_time

  def add_submission_time() self.submitted = Time.now end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @submissions }
    end
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
    @submission = Submission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/new
  # GET /submissions/new.json
  def new
    @submission = Submission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @submission }
    end
  end

  # GET /submissions/1/edit
  def edit
    @submission = Submission.find(params[:id])
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(params[:submission])

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render json: @submission, status: :created, location: @submission }
      else
        format.html { render action: "new" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /submissions/1
  # PUT /submissions/1.json
  def update
    @submission = Submission.find(params[:id])

    respond_to do |format|
      if @submission.update_attributes(params[:submission])
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_field :note %>
  </div>
  <div class="field">
    <%= f.label :submitted %><br />
    <%= f.datetime_select :submitted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Listing submissions</h1>

<table>
  <tr>
    <th>Note</th>
    <th>Submitted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @submissions.each do |submission| %>
  <tr>
    <td><%= submission.note %></td>
    <td><%= submission.submitted %></td>
    <td><%= link_to 'Show', submission %></td>
    <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
    <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Note:</b>
  <%= @submission.note %>
</p>

<p>
  <b>Submitted:</b>
  <%= @submission.submitted %>
</p>


<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>