config/routes.rb
Brainbox::Application.routes.draw do
  get "preferences/index"

  get "preferences/edit", :as => :preferences

  resources :comments
  resources :calendar_events
  resources :super_files do
    collection do
      post 'create_many', :action => 'create_many'
    end
  end
  resources :sections do
    resources :assignments do
      resources :submissions
    end
  end
  resources :courses
  resources :schools

  get "help" => "help#index"
  get '/' => "home#index", :as => :home

  devise_for :users, :controllers => { 
    :confirmations => "confirmations",
    :passwords => "passwords",
    :registrations => "registrations",
    :sessions => "sessions",
  }

  # user entry points
  get '/admin/users' => "users#index", :as => :users
  get '/admin/users/new' => "users#new", :as => :new_user
  post '/admin/users/create' => "users#create", :as => :create_user
  get '/admin/users/edit' => "users#edit", :as => :edit_user
  patch '/admin/users/update' => "users#update", :as => :update_user
  get '/admin/users/:id' => "users#show", :as => :show_user

  get "home/index"

  root :to => "home#index"

  post 'feedback/create' => 'feedback#create', :as => 'feedback'
  get 'manage_courses' => 'sections#index', :as => 'manage_courses'
end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :name, :location, :logo, :style

  has_and_belongs_to_many :users

  validates :name, :presence => true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :style %><br />
    <%= f.text_field :style %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Logo</th>
    <th>Style</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.location %></td>
    <td><%= school.logo %></td>
    <td><%= school.style %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Location:</b>
  <%= @school.location %>
</p>

<p>
  <b>Logo:</b>
  <%= @school.logo %>
</p>

<p>
  <b>Style:</b>
  <%= @school.style %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>